//===- VCalcOps.h ----------------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// This file is further licensed as teaching material for the University of
// Alberta under MIT
//
//===----------------------------------------------------------------------===//

#ifndef VCALC_STANDALONETYPES_H
#define VCALC_STANDALONETYPES_H

/// Include the autogenerated declarations of the vcalc types
#define GET_TYPEDEF_CLASSES
#include "VCalc/Types.h.inc"


#endif // VCALC_STANDALONETYPES_H
